### ISSUE TITLE
Not working with Sony Cassette Deck

### ISSUE THREAD

**Issue by andrewferguson** [Ircama/Sony_SLink#3]
I'm trying to get this to work with my Sony TC-WE435 Cassette Deck. I am getting the device ID and control codes from [http://www.hifi-remote.com/sony/Sony_cass.htm](http://www.hifi-remote.com/sony/Sony_cass.htm), and I have confirmed that these codes (or at least the most basic ones, play,stop,fast-forward,rewind,record,pause) work with my deck by sending them as IR codes using [this project](https://github.com/probonopd/arduino-infrared-pronto).

I then connected a stereo 3.5mm jack to the Control-A1 II port, connected the lower section to Arduino GND and the tip to pin 2, and tried running
`slink.sendCommand(16, 50);`
which should start the cassette in deck A playing, but nothing happened.

I then tried the SLinkMonitor example, and looked at what happened when I manually pressed the play button for deck. I got "START,ac,40," or sometimes just "ac,40,". I'm not sure what this means or if it is helpful.

Do you know how I could get this working?

**Comment by Ircama** [comment]
Unfortunately I do not know that cassette deck, anyway I doubt that (DEC)16 could be the correct device code.

I think you should empirically try some other ones. Have a look to Sony_SLink.h (costants within SLINK_DEVICE_*).

Possibly, (dec)176=(hex)B0 (SLINK_DEVICE_MD) is the right one, or maybe (dec)160=(hex)A0, or (dec)164=(hex)A4, or (dec)167=(hex)A7. 

From http://boehmel.de/slink.htm, the device Code composition should be:

n n n n X y y y

where:

- nnnn = device number
- X = 0   write to device (this is the one you should use)
- X = 1   read from device
- yyy = sub-device number
- yyy = 111   all devices nnnn

It is easier to use SLINK_CMD_AMP_POWER_OFF for the early tests, verifying that the device is switched off, e.g.,

    slink.sendCommand(164, SLINK_CMD_AMP_POWER_OFF);

Check SwitchOnOffDevice.ino.

Regards
