### ISSUE TITLE
esp8266

### ISSUE THREAD

**Issue by Y0rk-code** [Ircama/Sony_SLink#4]
Hi,

I still have an old Sony STR-DB930 (still working after all these years :-) )

Got this project (basic functionality) running on an esp8266 with MQTT client. Thanks for the project.
(I'm going to interface with Home Assistant)

I have one question:

I connected the esp pin to the controlA1 with a 220Ohm resistor (esp io is 5 volt tolerant). 
This works.

You mentioned something about a diode "Do not forget a diode and a 220 Ohm resistor between slinkPin and the Control-A1 jack"

Is the diode really necessary, and how must it be placed?

**Comment by Ircama** [comment]
Here you are.
```

                    | /|    __________
Microcontroller ____|/ |___| 220 ohm  |_______ Control-A1 jack
                    |\ |   |__________|
                    | \|
```
    
This circuit protects the microcontroller against the internal +5.1V pull-up of S-LINK (e.g., when the microcontroller drives 0V) and against the maximum current drawn by the microcontroller in case of transmission collision (for instance when the microcontroller drives +Vdd, e.g., +5V, and S-LINK drops to Vss, e.g., 0V). Anyway, the diode is not strictly necessary (it also drops the 5.5V pulled up by some devices to less than 5V) and notice also that S-LINK can be shorted (providing in such case less than 1 mA).

I advise not to exceed the guaranteed voltage values of the chip; consider for instance adding a logic level converter.

**Comment by Y0rk-code** [comment]
Thank you for clarifying the diode issue.

My next step is implementing continuous monitoring the bus (in an interrupt service routine) and report status via mqtt.
For this I really have to learn how the protocol works :-)

**Comment by dev77-07** [comment]
> Thank you for clarifying the diode issue.
> 
> My next step is implementing continuous monitoring the bus (in an interrupt service routine) and report status via mqtt. For this I really have to learn how the protocol works :-)

I know this is old but any chance you ever got the monitoring working and reporting via mqtt?
