### ISSUE TITLE
How to connect with arduino

### ISSUE THREAD

**Issue by MarcoSuurlant** [Ircama/Sony_SLink#5]
Hi,

How to connect it to the arduino one?

Thanks

**Comment by Ircama** [comment]
Check [this](https://github.com/Ircama/Sony_SLink/blob/0e2f2bfdd8151ca7baba8c1f7ed00feb5d83ce48/Sony_SLink.cpp#L66-LL74) and [this](https://github.com/Ircama/Sony_SLink/issues/4#issuecomment-451699636).

**Comment by MarcoSuurlant** [comment]
Hi,

Thanks for the replay.
So if I understand you correctly this is then the circuit.

![32A54A95-0DAD-450A-B7FB-1FD57D9BD757](https://user-images.githubusercontent.com/9785030/56815547-ebd0bf80-6841-11e9-oritxbeufaprpcdcw.pngh

**Comment by MarcoSuurlant** [comment]
Hi,

Thanks for the replay.
So if I understand you correctly this is then the circuit.



Verstuurd vanaf mijn iPad
