### ISSUE TITLE
Track naming

### ISSUE THREAD

**Issue by flaep** [Ircama/Sony_SLink#7]
Hi,

I am trying to set tracknames on an connected MD Recorder.

Accordung to http://boehmel.de/slink.htm
Pattern is the following: 9A TT 00 00 [14d x CC] 

Am I correct that Sony_Slink Code can only issue 3 commands in one slink.sendCommand()?

I tried to use `slink.sendCommand(SLINK_DEVICE_MD, 154, 01, 00, 00, 65);` To name the first track "A".

This fails to compile:

> Sony_SLink.h:112:10: note: candidate: void Slink::sendCommand(unsigned int, unsigned int, int, int)
> 
>      void sendCommand(unsigned int deviceId = 0x00, unsigned int commandId1 = 0x00, int commandId2 = -1, int commandId3 = -1);
> 
>           ^~~~~~~~~~~
> 
> G:\arduino\arduino-1.8.12\libraries\Sony_SLink/Sony_SLink.h:112:10: note:   candidate expects 4 arguments, 5 provided
> 
> exit status 1
> no matching function for call to 'Slink::sendCommand(int, int, int, int, int)'

Can I just extend 

`void Slink::` in Sony_SLink.cpp and 
`class Slink
{` in Sony_Slink.h ?

If so. How?
I have very basic coding knowledge and nearly none with arduino

Thank You for creating the Sony_Link Code

**Comment by michaelshiel** [comment]
This function should probably take an array of data and a length and loop over that, but as a short term fix since you haven't done Arduino before I would just add more `commandId#` parameters and copy paste additional
```
if (commandId#>=0)
    _writeByte(commandId#); // Send an additional Command-Code (one byte)
```
blocks for as many as you needed.

**Comment by flaep** [comment]
I already did exactly that and it works.

Thank you for your reply.
